### ISSUE TITLE
Evaluate WEBM as well?

### ISSUE THREAD

**Issue by walles** [TomasHubelbauer/markdown-webp#1]
What the title says. Maybe evaluate WEBM as well?

I just did a very unscientific experiment and my WEBM turned out 75% smaller than the corresponding WEBP.

**Comment by TomasHubelbauer** [comment]
You're talking about using WebM as an image instead of video? That sounds intriguing, I was under the impression it was using WebP internally so it is interesting to hear it comes out smaller. Do you have a sample WebM file I could test with to see if it works as a MarkDown image on GitHub and in VS Code?

BTW the reason I am asking about using it as a picture and not video is the same as for the other video formats I considered: you can't embed them in a MarkDown file and have them be playable on GitHub and in VS Code.

**Comment by walles** [comment]
I used <https://mconverter.eu/convert/webp/webm/> to convert your existing `test.webp` file to a WEBM, came out at 29,391B.

Unfortunately I'm not allowed to attach WEBM files to comments apparently so you can't have it :/.

**Comment by TomasHubelbauer** [comment]
I used the same converted and indeed the image comes out smaller. Unfortunately though, it won't preview in VS Code even when opened as a direct file. Also won't preview when used as an image in MarkDown. I am pretty sure it won't preview on GitHub either given this.
